/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyticsGetLinkEvents } from "../funcs/analytics-get-link-events.js";
import { analyticsGetSummary } from "../funcs/analytics-get-summary.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Analytics extends ClientSDK {
  /**
   * Summary statistics
   *
   * @remarks
   * Returns total link count and total click count, optionally filtered by a date range.
   */
  async getSummary(
    request?: operations.GetV1AnalyticsSummaryRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1AnalyticsSummaryResponse> {
    return unwrapAsync(analyticsGetSummary(
      this,
      request,
      options,
    ));
  }

  /**
   * Click events for a link
   *
   * @remarks
   * Returns paginated click events for a specific short link, with device, geo, and referrer breakdown.
   */
  async getLinkEvents(
    request: operations.GetV1AnalyticsLinksShortCodeRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1AnalyticsLinksShortCodeResponse,
      { page: number }
    >
  > {
    return unwrapResultIterator(analyticsGetLinkEvents(
      this,
      request,
      options,
    ));
  }
}
