/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationTest } from "../funcs/authentication-test.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Validate API key
   *
   * @remarks
   * Validates the API key and returns the connected account details. Useful for verifying credentials during SDK setup.
   */
  async test(
    options?: RequestOptions,
  ): Promise<operations.GetV1AuthTestResponse> {
    return unwrapAsync(authenticationTest(
      this,
      options,
    ));
  }
}
