/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversionsList } from "../funcs/conversions-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Conversions extends ClientSDK {
  /**
   * List conversions
   *
   * @remarks
   * Returns a paginated list of conversion events (leads and sales), ordered by creation date descending.
   */
  async list(
    request?: operations.GetV1ConversionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetV1ConversionsResponse, { page: number }>
  > {
    return unwrapResultIterator(conversionsList(
      this,
      request,
      options,
    ));
  }
}
