/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsGet } from "../funcs/domains-get.js";
import { domainsList } from "../funcs/domains-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Domains extends ClientSDK {
  /**
   * List domains
   *
   * @remarks
   * Returns all custom domains attached to the workspace, ordered by creation date descending.
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetV1DomainsResponse> {
    return unwrapAsync(domainsList(
      this,
      options,
    ));
  }

  /**
   * Get a domain
   *
   * @remarks
   * Returns a single domain including DNS verification records.
   */
  async get(
    request: operations.GetV1DomainsIdRequest,
    options?: RequestOptions,
  ): Promise<models.DomainDetail> {
    return unwrapAsync(domainsGet(
      this,
      request,
      options,
    ));
  }
}
