/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exportsExportLinksAsCsv } from "../funcs/exports-export-links-as-csv.js";
import { exportsGetClicksCsv } from "../funcs/exports-get-clicks-csv.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Exports extends ClientSDK {
  /**
   * Export links as CSV
   *
   * @remarks
   * Downloads all links as a CSV file. Authenticate via `?api_key=` query param
   * (compatible with Excel "From Web") or via standard `Authorization`/`X-Api-Key` headers.
   */
  async exportLinksAsCsv(
    request: operations.GetFeedsLinksCsvRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(exportsExportLinksAsCsv(
      this,
      request,
      options,
    ));
  }

  /**
   * Export clicks as CSV
   *
   * @remarks
   * Downloads click events for a specific short link as CSV.
   */
  async getClicksCsv(
    request: operations.GetFeedsClicksCsvRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(exportsGetClicksCsv(
      this,
      request,
      options,
    ));
  }
}
