/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linksBulkCreate } from "../funcs/links-bulk-create.js";
import { linksCreate } from "../funcs/links-create.js";
import { linksDelete } from "../funcs/links-delete.js";
import { linksGet } from "../funcs/links-get.js";
import { linksHealthCheck } from "../funcs/links-health-check.js";
import { linksList } from "../funcs/links-list.js";
import { linksUpdate } from "../funcs/links-update.js";
import { linksUpsert } from "../funcs/links-upsert.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Links extends ClientSDK {
  /**
   * Health check
   *
   * @remarks
   * Returns `ok` if the API is up. No authentication required.
   */
  async healthCheck(
    options?: RequestOptions,
  ): Promise<operations.GetHealthResponse> {
    return unwrapAsync(linksHealthCheck(
      this,
      options,
    ));
  }

  /**
   * List links
   *
   * @remarks
   * Returns a paginated list of short links, ordered by creation date descending.
   */
  async list(
    request?: operations.GetV1LinksRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1LinksResponse, { page: number }>> {
    return unwrapResultIterator(linksList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a link
   *
   * @remarks
   * Creates a new short link. The URL is screened against a local blocklist,
   * a database blocklist, and Google Safe Browsing before being saved.
   */
  async create(
    request: operations.PostV1LinksRequest,
    options?: RequestOptions,
  ): Promise<models.Link> {
    return unwrapAsync(linksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Upsert a link
   *
   * @remarks
   * Creates a link with the given `shortCode` if it does not exist, or updates it if it does.
   * Useful for idempotent integrations (e.g. Zapier).
   */
  async upsert(
    request: operations.PutV1LinksShortCodeRequest,
    options?: RequestOptions,
  ): Promise<models.Link> {
    return unwrapAsync(linksUpsert(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a link
   */
  async get(
    request: operations.GetV1LinksShortCodeRequest,
    options?: RequestOptions,
  ): Promise<models.Link> {
    return unwrapAsync(linksGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a link
   *
   * @remarks
   * Partial update — only include fields you want to change.
   */
  async update(
    request: operations.PatchV1LinksShortCodeRequest,
    options?: RequestOptions,
  ): Promise<models.Link> {
    return unwrapAsync(linksUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a link
   */
  async delete(
    request: operations.DeleteV1LinksShortCodeRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1LinksShortCodeResponse> {
    return unwrapAsync(linksDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk create links
   *
   * @remarks
   * Creates up to 1,000 short links in a single request. Each link is screened
   * against safety checks. Links that fail are skipped and reported in `errors`.
   * The response is `201` even when some links are skipped.
   */
  async bulkCreate(
    request: operations.PostV1LinksBulkRequest,
    options?: RequestOptions,
  ): Promise<models.BulkCreateResult> {
    return unwrapAsync(linksBulkCreate(
      this,
      request,
      options,
    ));
  }
}
