/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listsCreate } from "../funcs/lists-create.js";
import { listsDelete } from "../funcs/lists-delete.js";
import { listsGetAll } from "../funcs/lists-get-all.js";
import { listsGet } from "../funcs/lists-get.js";
import { listsUpdate } from "../funcs/lists-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Lists extends ClientSDK {
  /**
   * List all lists
   */
  async getAll(
    options?: RequestOptions,
  ): Promise<operations.GetV1ListsResponse> {
    return unwrapAsync(listsGetAll(
      this,
      options,
    ));
  }

  /**
   * Create a list
   */
  async create(
    request: models.ListInput,
    options?: RequestOptions,
  ): Promise<models.List> {
    return unwrapAsync(listsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a list
   */
  async get(
    request: operations.GetV1ListsIdRequest,
    options?: RequestOptions,
  ): Promise<models.List> {
    return unwrapAsync(listsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a list
   */
  async update(
    request: operations.PatchV1ListsIdRequest,
    options?: RequestOptions,
  ): Promise<models.List> {
    return unwrapAsync(listsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a list
   */
  async delete(
    request: operations.DeleteV1ListsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1ListsIdResponse> {
    return unwrapAsync(listsDelete(
      this,
      request,
      options,
    ));
  }
}
