/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { qrCodesCreate } from "../funcs/qr-codes-create.js";
import { qrCodesDelete } from "../funcs/qr-codes-delete.js";
import { qrCodesGet } from "../funcs/qr-codes-get.js";
import { qrCodesList } from "../funcs/qr-codes-list.js";
import { qrCodesUpdate } from "../funcs/qr-codes-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class QrCodes extends ClientSDK {
  /**
   * List QR codes
   */
  async list(
    request?: operations.GetV1QrCodesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetV1QrCodesResponse, { page: number }>> {
    return unwrapResultIterator(qrCodesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a QR code
   */
  async create(
    request: operations.PostV1QrCodesRequest,
    options?: RequestOptions,
  ): Promise<models.QrCode> {
    return unwrapAsync(qrCodesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a QR code
   */
  async get(
    request: operations.GetV1QrCodesIdRequest,
    options?: RequestOptions,
  ): Promise<models.QrCode> {
    return unwrapAsync(qrCodesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a QR code
   */
  async update(
    request: operations.PatchV1QrCodesIdRequest,
    options?: RequestOptions,
  ): Promise<models.QrCode> {
    return unwrapAsync(qrCodesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a QR code
   */
  async delete(
    request: operations.DeleteV1QrCodesIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1QrCodesIdResponse> {
    return unwrapAsync(qrCodesDelete(
      this,
      request,
      options,
    ));
  }
}
