/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Analytics } from "./analytics.js";
import { Authentication } from "./authentication.js";
import { Conversions } from "./conversions.js";
import { Domains } from "./domains.js";
import { Exports } from "./exports.js";
import { Links } from "./links.js";
import { Lists } from "./lists.js";
import { QrCodes } from "./qr-codes.js";
import { Tags } from "./tags.js";
import { Tracking } from "./tracking.js";
import { UtmTemplates } from "./utm-templates.js";
import { Webhooks } from "./webhooks.js";
import { Workspaces } from "./workspaces.js";

export class Linkkit extends ClientSDK {
  private _links?: Links;
  get links(): Links {
    return (this._links ??= new Links(this._options));
  }

  private _tags?: Tags;
  get tags(): Tags {
    return (this._tags ??= new Tags(this._options));
  }

  private _qrCodes?: QrCodes;
  get qrCodes(): QrCodes {
    return (this._qrCodes ??= new QrCodes(this._options));
  }

  private _analytics?: Analytics;
  get analytics(): Analytics {
    return (this._analytics ??= new Analytics(this._options));
  }

  private _lists?: Lists;
  get lists(): Lists {
    return (this._lists ??= new Lists(this._options));
  }

  private _utmTemplates?: UtmTemplates;
  get utmTemplates(): UtmTemplates {
    return (this._utmTemplates ??= new UtmTemplates(this._options));
  }

  private _conversions?: Conversions;
  get conversions(): Conversions {
    return (this._conversions ??= new Conversions(this._options));
  }

  private _tracking?: Tracking;
  get tracking(): Tracking {
    return (this._tracking ??= new Tracking(this._options));
  }

  private _domains?: Domains;
  get domains(): Domains {
    return (this._domains ??= new Domains(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  private _workspaces?: Workspaces;
  get workspaces(): Workspaces {
    return (this._workspaces ??= new Workspaces(this._options));
  }

  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }

  private _exports?: Exports;
  get exports(): Exports {
    return (this._exports ??= new Exports(this._options));
  }
}
