/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsCreate } from "../funcs/tags-create.js";
import { tagsDelete } from "../funcs/tags-delete.js";
import { tagsGet } from "../funcs/tags-get.js";
import { tagsList } from "../funcs/tags-list.js";
import { tagsUpdate } from "../funcs/tags-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tags extends ClientSDK {
  /**
   * List tags
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetV1TagsResponse> {
    return unwrapAsync(tagsList(
      this,
      options,
    ));
  }

  /**
   * Create a tag
   */
  async create(
    request: models.TagInput,
    options?: RequestOptions,
  ): Promise<models.Tag> {
    return unwrapAsync(tagsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a tag
   */
  async get(
    request: operations.GetV1TagsIdRequest,
    options?: RequestOptions,
  ): Promise<models.Tag> {
    return unwrapAsync(tagsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a tag
   */
  async update(
    request: operations.PatchV1TagsIdRequest,
    options?: RequestOptions,
  ): Promise<models.Tag> {
    return unwrapAsync(tagsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a tag
   */
  async delete(
    request: operations.DeleteV1TagsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1TagsIdResponse> {
    return unwrapAsync(tagsDelete(
      this,
      request,
      options,
    ));
  }
}
