/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trackingLead } from "../funcs/tracking-lead.js";
import { trackingTrackSale } from "../funcs/tracking-track-sale.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tracking extends ClientSDK {
  /**
   * Track a lead
   *
   * @remarks
   * Records a lead conversion event. Authenticated via a publishable key (not an API key).
   * Pass `lkclid` (the Linkkit click ID from the `?lkclid=` query parameter appended to your
   * short link) to attribute the lead to a specific click.
   */
  async lead(
    request: operations.PostTrackLeadRequest,
    options?: RequestOptions,
  ): Promise<models.Conversion> {
    return unwrapAsync(trackingLead(
      this,
      request,
      options,
    ));
  }

  /**
   * Track a sale
   *
   * @remarks
   * Records a sale conversion event. Authenticated via a publishable key (not an API key).
   * Pass `lkclid` (the Linkkit click ID) to attribute the sale to a specific click.
   */
  async trackSale(
    request: operations.PostTrackSaleRequest,
    options?: RequestOptions,
  ): Promise<models.Conversion> {
    return unwrapAsync(trackingTrackSale(
      this,
      request,
      options,
    ));
  }
}
