/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { utmTemplatesCreate } from "../funcs/utm-templates-create.js";
import { utmTemplatesDelete } from "../funcs/utm-templates-delete.js";
import { utmTemplatesGet } from "../funcs/utm-templates-get.js";
import { utmTemplatesList } from "../funcs/utm-templates-list.js";
import { utmTemplatesUpdate } from "../funcs/utm-templates-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UtmTemplates extends ClientSDK {
  /**
   * List UTM templates
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetV1UtmTemplatesResponse> {
    return unwrapAsync(utmTemplatesList(
      this,
      options,
    ));
  }

  /**
   * Create a UTM template
   */
  async create(
    request: operations.PostV1UtmTemplatesRequest,
    options?: RequestOptions,
  ): Promise<models.UtmTemplate> {
    return unwrapAsync(utmTemplatesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a UTM template
   */
  async get(
    request: operations.GetV1UtmTemplatesIdRequest,
    options?: RequestOptions,
  ): Promise<models.UtmTemplate> {
    return unwrapAsync(utmTemplatesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a UTM template
   */
  async update(
    request: operations.PatchV1UtmTemplatesIdRequest,
    options?: RequestOptions,
  ): Promise<models.UtmTemplate> {
    return unwrapAsync(utmTemplatesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a UTM template
   */
  async delete(
    request: operations.DeleteV1UtmTemplatesIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1UtmTemplatesIdResponse> {
    return unwrapAsync(utmTemplatesDelete(
      this,
      request,
      options,
    ));
  }
}
