/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksSubscribe } from "../funcs/webhooks-subscribe.js";
import { webhooksUnsubscribe } from "../funcs/webhooks-unsubscribe.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Subscribe to an event
   *
   * @remarks
   * Creates a webhook subscription. Linkkit will POST to `target_url` whenever
   * the specified event occurs. The response includes a `secret` for verifying
   * the `X-Linkkit-Signature` HMAC-SHA256 header. Store it securely — returned once only.
   */
  async subscribe(
    request: operations.PostV1HooksRequest,
    options?: RequestOptions,
  ): Promise<models.Webhook> {
    return unwrapAsync(webhooksSubscribe(
      this,
      request,
      options,
    ));
  }

  /**
   * Unsubscribe
   *
   * @remarks
   * Deletes a webhook subscription.
   */
  async unsubscribe(
    request: operations.DeleteV1HooksIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1HooksIdResponse> {
    return unwrapAsync(webhooksUnsubscribe(
      this,
      request,
      options,
    ));
  }
}
