/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesList } from "../funcs/workspaces-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Workspaces extends ClientSDK {
  /**
   * List workspaces
   *
   * @remarks
   * Returns all workspaces the API key belongs to, including the caller's role in each.
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetV1WorkspacesResponse> {
    return unwrapAsync(workspacesList(
      this,
      options,
    ));
  }
}
