/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @getlinkkit/linkkit SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx linksHealthCheck.example.ts
 */

import { Linkkit } from "@getlinkkit/linkkit";

const linkkit = new Linkkit();

async function main() {
  const result = await linkkit.links.healthCheck();

  console.log(result);
}

main().catch(console.error);
