workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Linkkit API:
        inputs:
            - location: out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/linkkit/linkkit/linkkit-api
targets:
    linkkit:
        target: typescript
        source: Linkkit API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/linkkit/linkkit/linkkit-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
