/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV1TagsIdRequest = {
  id: string;
};

/**
 * Tag deleted
 */
export type DeleteV1TagsIdResponse = {
  deleted?: boolean | undefined;
};

/** @internal */
export type DeleteV1TagsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1TagsIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1TagsIdRequest$Outbound,
  DeleteV1TagsIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1TagsIdRequestToJSON(
  deleteV1TagsIdRequest: DeleteV1TagsIdRequest,
): string {
  return JSON.stringify(
    DeleteV1TagsIdRequest$outboundSchema.parse(deleteV1TagsIdRequest),
  );
}

/** @internal */
export const DeleteV1TagsIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1TagsIdResponse,
  unknown
> = z.object({
  deleted: types.optional(types.boolean()),
});

export function deleteV1TagsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1TagsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1TagsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1TagsIdResponse' from JSON`,
  );
}
