/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV1UtmTemplatesIdRequest = {
  id: string;
};

/**
 * UTM template deleted
 */
export type DeleteV1UtmTemplatesIdResponse = {
  deleted?: boolean | undefined;
};

/** @internal */
export type DeleteV1UtmTemplatesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1UtmTemplatesIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1UtmTemplatesIdRequest$Outbound,
  DeleteV1UtmTemplatesIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1UtmTemplatesIdRequestToJSON(
  deleteV1UtmTemplatesIdRequest: DeleteV1UtmTemplatesIdRequest,
): string {
  return JSON.stringify(
    DeleteV1UtmTemplatesIdRequest$outboundSchema.parse(
      deleteV1UtmTemplatesIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV1UtmTemplatesIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1UtmTemplatesIdResponse,
  unknown
> = z.object({
  deleted: types.optional(types.boolean()),
});

export function deleteV1UtmTemplatesIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1UtmTemplatesIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1UtmTemplatesIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1UtmTemplatesIdResponse' from JSON`,
  );
}
