/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV1QrCodesIdRequest = {
  id: string;
};

/**
 * QR code deleted
 */
export type DeleteV1QrCodesIdResponse = {
  deleted?: boolean | undefined;
};

/** @internal */
export type DeleteV1QrCodesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1QrCodesIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1QrCodesIdRequest$Outbound,
  DeleteV1QrCodesIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1QrCodesIdRequestToJSON(
  deleteV1QrCodesIdRequest: DeleteV1QrCodesIdRequest,
): string {
  return JSON.stringify(
    DeleteV1QrCodesIdRequest$outboundSchema.parse(deleteV1QrCodesIdRequest),
  );
}

/** @internal */
export const DeleteV1QrCodesIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1QrCodesIdResponse,
  unknown
> = z.object({
  deleted: types.optional(types.boolean()),
});

export function deleteV1QrCodesIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1QrCodesIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1QrCodesIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1QrCodesIdResponse' from JSON`,
  );
}
