/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeleteV1HooksIdRequest = {
  id: string;
};

/**
 * Webhook deleted
 */
export type DeleteV1HooksIdResponseBody = {
  unsubscribed?: boolean | undefined;
};

export type DeleteV1HooksIdResponse =
  | models.ErrorT
  | DeleteV1HooksIdResponseBody;

/** @internal */
export type DeleteV1HooksIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1HooksIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1HooksIdRequest$Outbound,
  DeleteV1HooksIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1HooksIdRequestToJSON(
  deleteV1HooksIdRequest: DeleteV1HooksIdRequest,
): string {
  return JSON.stringify(
    DeleteV1HooksIdRequest$outboundSchema.parse(deleteV1HooksIdRequest),
  );
}

/** @internal */
export const DeleteV1HooksIdResponseBody$inboundSchema: z.ZodMiniType<
  DeleteV1HooksIdResponseBody,
  unknown
> = z.object({
  unsubscribed: types.optional(types.boolean()),
});

export function deleteV1HooksIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1HooksIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1HooksIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1HooksIdResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteV1HooksIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1HooksIdResponse,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => DeleteV1HooksIdResponseBody$inboundSchema),
]);

export function deleteV1HooksIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1HooksIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1HooksIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1HooksIdResponse' from JSON`,
  );
}
