/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV1ListsIdRequest = {
  id: string;
};

/**
 * List deleted
 */
export type DeleteV1ListsIdResponse = {
  deleted?: boolean | undefined;
};

/** @internal */
export type DeleteV1ListsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1ListsIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1ListsIdRequest$Outbound,
  DeleteV1ListsIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1ListsIdRequestToJSON(
  deleteV1ListsIdRequest: DeleteV1ListsIdRequest,
): string {
  return JSON.stringify(
    DeleteV1ListsIdRequest$outboundSchema.parse(deleteV1ListsIdRequest),
  );
}

/** @internal */
export const DeleteV1ListsIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1ListsIdResponse,
  unknown
> = z.object({
  deleted: types.optional(types.boolean()),
});

export function deleteV1ListsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1ListsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1ListsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1ListsIdResponse' from JSON`,
  );
}
