/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV1LinksShortCodeRequest = {
  shortCode: string;
};

/**
 * Link deleted
 */
export type DeleteV1LinksShortCodeResponse = {
  deleted?: boolean | undefined;
};

/** @internal */
export type DeleteV1LinksShortCodeRequest$Outbound = {
  shortCode: string;
};

/** @internal */
export const DeleteV1LinksShortCodeRequest$outboundSchema: z.ZodMiniType<
  DeleteV1LinksShortCodeRequest$Outbound,
  DeleteV1LinksShortCodeRequest
> = z.object({
  shortCode: z.string(),
});

export function deleteV1LinksShortCodeRequestToJSON(
  deleteV1LinksShortCodeRequest: DeleteV1LinksShortCodeRequest,
): string {
  return JSON.stringify(
    DeleteV1LinksShortCodeRequest$outboundSchema.parse(
      deleteV1LinksShortCodeRequest,
    ),
  );
}

/** @internal */
export const DeleteV1LinksShortCodeResponse$inboundSchema: z.ZodMiniType<
  DeleteV1LinksShortCodeResponse,
  unknown
> = z.object({
  deleted: types.optional(types.boolean()),
});

export function deleteV1LinksShortCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1LinksShortCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1LinksShortCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1LinksShortCodeResponse' from JSON`,
  );
}
