/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1TagsIdRequest = {
  id: string;
};

/** @internal */
export type GetV1TagsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1TagsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1TagsIdRequest$Outbound,
  GetV1TagsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1TagsIdRequestToJSON(
  getV1TagsIdRequest: GetV1TagsIdRequest,
): string {
  return JSON.stringify(
    GetV1TagsIdRequest$outboundSchema.parse(getV1TagsIdRequest),
  );
}
