/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * List of workspaces
 */
export type GetV1WorkspacesResponse = {
  data?: Array<models.Workspace> | undefined;
  meta?: models.MetaTotal | undefined;
};

/** @internal */
export const GetV1WorkspacesResponse$inboundSchema: z.ZodMiniType<
  GetV1WorkspacesResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.Workspace$inboundSchema)),
  meta: types.optional(models.MetaTotal$inboundSchema),
});

export function getV1WorkspacesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1WorkspacesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1WorkspacesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1WorkspacesResponse' from JSON`,
  );
}
