/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1LinksShortCodeRequest = {
  shortCode: string;
};

/** @internal */
export type GetV1LinksShortCodeRequest$Outbound = {
  shortCode: string;
};

/** @internal */
export const GetV1LinksShortCodeRequest$outboundSchema: z.ZodMiniType<
  GetV1LinksShortCodeRequest$Outbound,
  GetV1LinksShortCodeRequest
> = z.object({
  shortCode: z.string(),
});

export function getV1LinksShortCodeRequestToJSON(
  getV1LinksShortCodeRequest: GetV1LinksShortCodeRequest,
): string {
  return JSON.stringify(
    GetV1LinksShortCodeRequest$outboundSchema.parse(getV1LinksShortCodeRequest),
  );
}
