/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetFeedsLinksCsvRequest = {
  apiKey: string;
  search?: string | undefined;
  listId?: string | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export type GetFeedsLinksCsvRequest$Outbound = {
  api_key: string;
  search?: string | undefined;
  list_id?: string | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const GetFeedsLinksCsvRequest$outboundSchema: z.ZodMiniType<
  GetFeedsLinksCsvRequest$Outbound,
  GetFeedsLinksCsvRequest
> = z.pipe(
  z.object({
    apiKey: z.string(),
    search: z.optional(z.string()),
    listId: z.optional(z.string()),
    isActive: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
      listId: "list_id",
      isActive: "is_active",
    });
  }),
);

export function getFeedsLinksCsvRequestToJSON(
  getFeedsLinksCsvRequest: GetFeedsLinksCsvRequest,
): string {
  return JSON.stringify(
    GetFeedsLinksCsvRequest$outboundSchema.parse(getFeedsLinksCsvRequest),
  );
}
