/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * API is healthy
 */
export type GetHealthResponseBody = {
  status?: string | undefined;
};

export type GetHealthResponse = models.ErrorT | GetHealthResponseBody;

/** @internal */
export const GetHealthResponseBody$inboundSchema: z.ZodMiniType<
  GetHealthResponseBody,
  unknown
> = z.object({
  status: types.optional(types.string()),
});

export function getHealthResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetHealthResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthResponseBody' from JSON`,
  );
}

/** @internal */
export const GetHealthResponse$inboundSchema: z.ZodMiniType<
  GetHealthResponse,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => GetHealthResponseBody$inboundSchema),
]);

export function getHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthResponse' from JSON`,
  );
}
