/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1LinksRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  /**
   * Filter by URL or title (case-insensitive substring match)
   */
  search?: string | undefined;
  /**
   * Filter by list UUID
   */
  listId?: string | undefined;
  /**
   * Filter by active status
   */
  isActive?: boolean | undefined;
};

/**
 * Paginated list of links
 */
export type GetV1LinksResponseBody = {
  data?: Array<models.Link> | undefined;
  meta?: models.Meta | undefined;
};

export type GetV1LinksResponse = {
  result: GetV1LinksResponseBody;
};

/** @internal */
export type GetV1LinksRequest$Outbound = {
  page: number;
  limit: number;
  search?: string | undefined;
  list_id?: string | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const GetV1LinksRequest$outboundSchema: z.ZodMiniType<
  GetV1LinksRequest$Outbound,
  GetV1LinksRequest
> = z.pipe(
  z.object({
    page: z._default(z.int(), 1),
    limit: z._default(z.int(), 20),
    search: z.optional(z.string()),
    listId: z.optional(z.string()),
    isActive: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
      isActive: "is_active",
    });
  }),
);

export function getV1LinksRequestToJSON(
  getV1LinksRequest: GetV1LinksRequest,
): string {
  return JSON.stringify(
    GetV1LinksRequest$outboundSchema.parse(getV1LinksRequest),
  );
}

/** @internal */
export const GetV1LinksResponseBody$inboundSchema: z.ZodMiniType<
  GetV1LinksResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(models.Link$inboundSchema)),
  meta: types.optional(models.Meta$inboundSchema),
});

export function getV1LinksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LinksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LinksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LinksResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LinksResponse$inboundSchema: z.ZodMiniType<
  GetV1LinksResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => GetV1LinksResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1LinksResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LinksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LinksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LinksResponse' from JSON`,
  );
}
