/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * All lists ordered by name
 */
export type GetV1ListsResponseBody = {
  data?: Array<models.List> | undefined;
  meta?: models.MetaTotal | undefined;
};

export type GetV1ListsResponse = models.ErrorT | GetV1ListsResponseBody;

/** @internal */
export const GetV1ListsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1ListsResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(models.List$inboundSchema)),
  meta: types.optional(models.MetaTotal$inboundSchema),
});

export function getV1ListsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ListsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ListsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ListsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ListsResponse$inboundSchema: z.ZodMiniType<
  GetV1ListsResponse,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => GetV1ListsResponseBody$inboundSchema),
]);

export function getV1ListsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ListsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ListsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ListsResponse' from JSON`,
  );
}
