/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * API key is valid
 */
export type GetV1AuthTestResponse = {
  userId?: string | undefined;
  workspaceId?: string | null | undefined;
  email?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const GetV1AuthTestResponse$inboundSchema: z.ZodMiniType<
  GetV1AuthTestResponse,
  unknown
> = z.pipe(
  z.object({
    user_id: types.optional(types.string()),
    workspace_id: z.optional(z.nullable(types.string())),
    email: z.optional(z.nullable(types.string())),
    name: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "user_id": "userId",
      "workspace_id": "workspaceId",
    });
  }),
);

export function getV1AuthTestResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AuthTestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AuthTestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AuthTestResponse' from JSON`,
  );
}
