/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1AnalyticsLinksShortCodeRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  shortCode: string;
  from?: Date | undefined;
  to?: Date | undefined;
};

/**
 * Paginated click events
 */
export type GetV1AnalyticsLinksShortCodeResponseBody = {
  data?: Array<models.Click> | undefined;
  meta?: models.Meta | undefined;
};

export type GetV1AnalyticsLinksShortCodeResponse = {
  result: GetV1AnalyticsLinksShortCodeResponseBody;
};

/** @internal */
export type GetV1AnalyticsLinksShortCodeRequest$Outbound = {
  page: number;
  limit: number;
  shortCode: string;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetV1AnalyticsLinksShortCodeRequest$outboundSchema: z.ZodMiniType<
  GetV1AnalyticsLinksShortCodeRequest$Outbound,
  GetV1AnalyticsLinksShortCodeRequest
> = z.object({
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 20),
  shortCode: z.string(),
  from: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  to: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function getV1AnalyticsLinksShortCodeRequestToJSON(
  getV1AnalyticsLinksShortCodeRequest: GetV1AnalyticsLinksShortCodeRequest,
): string {
  return JSON.stringify(
    GetV1AnalyticsLinksShortCodeRequest$outboundSchema.parse(
      getV1AnalyticsLinksShortCodeRequest,
    ),
  );
}

/** @internal */
export const GetV1AnalyticsLinksShortCodeResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AnalyticsLinksShortCodeResponseBody, unknown> = z.object({
    data: types.optional(z.array(models.Click$inboundSchema)),
    meta: types.optional(models.Meta$inboundSchema),
  });

export function getV1AnalyticsLinksShortCodeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AnalyticsLinksShortCodeResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AnalyticsLinksShortCodeResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AnalyticsLinksShortCodeResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1AnalyticsLinksShortCodeResponse$inboundSchema: z.ZodMiniType<
  GetV1AnalyticsLinksShortCodeResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() =>
      GetV1AnalyticsLinksShortCodeResponseBody$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1AnalyticsLinksShortCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AnalyticsLinksShortCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AnalyticsLinksShortCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AnalyticsLinksShortCodeResponse' from JSON`,
  );
}
