/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1ConversionsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  /**
   * Filter by your internal customer ID
   */
  customerExternalId?: string | undefined;
  /**
   * Filter by invoice ID
   */
  invoiceId?: string | undefined;
  /**
   * Filter by conversion type
   */
  type?: models.ConversionType | undefined;
  /**
   * ISO 8601 start datetime (inclusive)
   */
  from?: Date | undefined;
  /**
   * ISO 8601 end datetime (inclusive)
   */
  to?: Date | undefined;
};

/**
 * Paginated list of conversions
 */
export type GetV1ConversionsResponseBody = {
  data?: Array<models.Conversion> | undefined;
  meta?: models.Meta | undefined;
};

export type GetV1ConversionsResponse = {
  result: GetV1ConversionsResponseBody;
};

/** @internal */
export type GetV1ConversionsRequest$Outbound = {
  page: number;
  limit: number;
  customer_external_id?: string | undefined;
  invoice_id?: string | undefined;
  type?: string | undefined;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetV1ConversionsRequest$outboundSchema: z.ZodMiniType<
  GetV1ConversionsRequest$Outbound,
  GetV1ConversionsRequest
> = z.pipe(
  z.object({
    page: z._default(z.int(), 1),
    limit: z._default(z.int(), 20),
    customerExternalId: z.optional(z.string()),
    invoiceId: z.optional(z.string()),
    type: z.optional(models.ConversionType$outboundSchema),
    from: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    to: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerExternalId: "customer_external_id",
      invoiceId: "invoice_id",
    });
  }),
);

export function getV1ConversionsRequestToJSON(
  getV1ConversionsRequest: GetV1ConversionsRequest,
): string {
  return JSON.stringify(
    GetV1ConversionsRequest$outboundSchema.parse(getV1ConversionsRequest),
  );
}

/** @internal */
export const GetV1ConversionsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1ConversionsResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(models.Conversion$inboundSchema)),
  meta: types.optional(models.Meta$inboundSchema),
});

export function getV1ConversionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConversionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConversionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConversionsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ConversionsResponse$inboundSchema: z.ZodMiniType<
  GetV1ConversionsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => GetV1ConversionsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1ConversionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConversionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConversionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConversionsResponse' from JSON`,
  );
}
