/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * All tags ordered by name
 */
export type GetV1TagsResponseBody = {
  data?: Array<models.Tag> | undefined;
  meta?: models.MetaTotal | undefined;
};

export type GetV1TagsResponse = models.ErrorT | GetV1TagsResponseBody;

/** @internal */
export const GetV1TagsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1TagsResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(models.Tag$inboundSchema)),
  meta: types.optional(models.MetaTotal$inboundSchema),
});

export function getV1TagsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1TagsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1TagsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1TagsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1TagsResponse$inboundSchema: z.ZodMiniType<
  GetV1TagsResponse,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => GetV1TagsResponseBody$inboundSchema),
]);

export function getV1TagsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1TagsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1TagsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1TagsResponse' from JSON`,
  );
}
