/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * List of domains
 */
export type GetV1DomainsResponse = {
  data?: Array<models.Domain> | undefined;
  meta?: models.MetaTotal | undefined;
};

/** @internal */
export const GetV1DomainsResponse$inboundSchema: z.ZodMiniType<
  GetV1DomainsResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.Domain$inboundSchema)),
  meta: types.optional(models.MetaTotal$inboundSchema),
});

export function getV1DomainsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1DomainsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1DomainsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1DomainsResponse' from JSON`,
  );
}
