/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1QrCodesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
};

/**
 * Paginated list of QR codes
 */
export type GetV1QrCodesResponseBody = {
  data?: Array<models.QrCode> | undefined;
  meta?: models.Meta | undefined;
};

export type GetV1QrCodesResponseResult =
  | models.ErrorT
  | GetV1QrCodesResponseBody;

export type GetV1QrCodesResponse = {
  result: models.ErrorT | GetV1QrCodesResponseBody;
};

/** @internal */
export type GetV1QrCodesRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const GetV1QrCodesRequest$outboundSchema: z.ZodMiniType<
  GetV1QrCodesRequest$Outbound,
  GetV1QrCodesRequest
> = z.object({
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 20),
});

export function getV1QrCodesRequestToJSON(
  getV1QrCodesRequest: GetV1QrCodesRequest,
): string {
  return JSON.stringify(
    GetV1QrCodesRequest$outboundSchema.parse(getV1QrCodesRequest),
  );
}

/** @internal */
export const GetV1QrCodesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1QrCodesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(models.QrCode$inboundSchema)),
  meta: types.optional(models.Meta$inboundSchema),
});

export function getV1QrCodesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1QrCodesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1QrCodesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1QrCodesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1QrCodesResponseResult$inboundSchema: z.ZodMiniType<
  GetV1QrCodesResponseResult,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => GetV1QrCodesResponseBody$inboundSchema),
]);

export function getV1QrCodesResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetV1QrCodesResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1QrCodesResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1QrCodesResponseResult' from JSON`,
  );
}

/** @internal */
export const GetV1QrCodesResponse$inboundSchema: z.ZodMiniType<
  GetV1QrCodesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: smartUnion([
      models.ErrorT$inboundSchema,
      z.lazy(() => GetV1QrCodesResponseBody$inboundSchema),
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function getV1QrCodesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1QrCodesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1QrCodesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1QrCodesResponse' from JSON`,
  );
}
