/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetFeedsClicksCsvRequest = {
  apiKey: string;
  shortCode: string;
  from?: Date | undefined;
  to?: Date | undefined;
};

/** @internal */
export type GetFeedsClicksCsvRequest$Outbound = {
  api_key: string;
  short_code: string;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetFeedsClicksCsvRequest$outboundSchema: z.ZodMiniType<
  GetFeedsClicksCsvRequest$Outbound,
  GetFeedsClicksCsvRequest
> = z.pipe(
  z.object({
    apiKey: z.string(),
    shortCode: z.string(),
    from: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    to: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
      shortCode: "short_code",
    });
  }),
);

export function getFeedsClicksCsvRequestToJSON(
  getFeedsClicksCsvRequest: GetFeedsClicksCsvRequest,
): string {
  return JSON.stringify(
    GetFeedsClicksCsvRequest$outboundSchema.parse(getFeedsClicksCsvRequest),
  );
}
