/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1QrCodesIdRequest = {
  id: string;
};

/** @internal */
export type GetV1QrCodesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1QrCodesIdRequest$outboundSchema: z.ZodMiniType<
  GetV1QrCodesIdRequest$Outbound,
  GetV1QrCodesIdRequest
> = z.object({
  id: z.string(),
});

export function getV1QrCodesIdRequestToJSON(
  getV1QrCodesIdRequest: GetV1QrCodesIdRequest,
): string {
  return JSON.stringify(
    GetV1QrCodesIdRequest$outboundSchema.parse(getV1QrCodesIdRequest),
  );
}
