/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1AnalyticsSummaryRequest = {
  /**
   * ISO 8601 start datetime (inclusive)
   */
  from?: Date | undefined;
  /**
   * ISO 8601 end datetime (inclusive)
   */
  to?: Date | undefined;
};

/**
 * Summary stats
 */
export type GetV1AnalyticsSummaryResponseBody = {
  totalLinks?: number | undefined;
  totalClicks?: number | undefined;
};

export type GetV1AnalyticsSummaryResponse =
  | models.ErrorT
  | GetV1AnalyticsSummaryResponseBody;

/** @internal */
export type GetV1AnalyticsSummaryRequest$Outbound = {
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetV1AnalyticsSummaryRequest$outboundSchema: z.ZodMiniType<
  GetV1AnalyticsSummaryRequest$Outbound,
  GetV1AnalyticsSummaryRequest
> = z.object({
  from: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  to: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function getV1AnalyticsSummaryRequestToJSON(
  getV1AnalyticsSummaryRequest: GetV1AnalyticsSummaryRequest,
): string {
  return JSON.stringify(
    GetV1AnalyticsSummaryRequest$outboundSchema.parse(
      getV1AnalyticsSummaryRequest,
    ),
  );
}

/** @internal */
export const GetV1AnalyticsSummaryResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AnalyticsSummaryResponseBody,
  unknown
> = z.pipe(
  z.object({
    total_links: types.optional(types.number()),
    total_clicks: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_links": "totalLinks",
      "total_clicks": "totalClicks",
    });
  }),
);

export function getV1AnalyticsSummaryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AnalyticsSummaryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AnalyticsSummaryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AnalyticsSummaryResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1AnalyticsSummaryResponse$inboundSchema: z.ZodMiniType<
  GetV1AnalyticsSummaryResponse,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => GetV1AnalyticsSummaryResponseBody$inboundSchema),
]);

export function getV1AnalyticsSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AnalyticsSummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AnalyticsSummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AnalyticsSummaryResponse' from JSON`,
  );
}
