/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1DomainsIdRequest = {
  id: string;
};

/** @internal */
export type GetV1DomainsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1DomainsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1DomainsIdRequest$Outbound,
  GetV1DomainsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1DomainsIdRequestToJSON(
  getV1DomainsIdRequest: GetV1DomainsIdRequest,
): string {
  return JSON.stringify(
    GetV1DomainsIdRequest$outboundSchema.parse(getV1DomainsIdRequest),
  );
}
