/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * All UTM templates ordered by name
 */
export type GetV1UtmTemplatesResponseBody = {
  data?: Array<models.UtmTemplate> | undefined;
  meta?: models.MetaTotal | undefined;
};

export type GetV1UtmTemplatesResponse =
  | models.ErrorT
  | GetV1UtmTemplatesResponseBody;

/** @internal */
export const GetV1UtmTemplatesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1UtmTemplatesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(models.UtmTemplate$inboundSchema)),
  meta: types.optional(models.MetaTotal$inboundSchema),
});

export function getV1UtmTemplatesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1UtmTemplatesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1UtmTemplatesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1UtmTemplatesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1UtmTemplatesResponse$inboundSchema: z.ZodMiniType<
  GetV1UtmTemplatesResponse,
  unknown
> = smartUnion([
  models.ErrorT$inboundSchema,
  z.lazy(() => GetV1UtmTemplatesResponseBody$inboundSchema),
]);

export function getV1UtmTemplatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1UtmTemplatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1UtmTemplatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1UtmTemplatesResponse' from JSON`,
  );
}
