/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1UtmTemplatesIdRequest = {
  id: string;
};

/** @internal */
export type GetV1UtmTemplatesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1UtmTemplatesIdRequest$outboundSchema: z.ZodMiniType<
  GetV1UtmTemplatesIdRequest$Outbound,
  GetV1UtmTemplatesIdRequest
> = z.object({
  id: z.string(),
});

export function getV1UtmTemplatesIdRequestToJSON(
  getV1UtmTemplatesIdRequest: GetV1UtmTemplatesIdRequest,
): string {
  return JSON.stringify(
    GetV1UtmTemplatesIdRequest$outboundSchema.parse(getV1UtmTemplatesIdRequest),
  );
}
