/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1ListsIdRequest = {
  id: string;
};

/** @internal */
export type GetV1ListsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1ListsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1ListsIdRequest$Outbound,
  GetV1ListsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1ListsIdRequestToJSON(
  getV1ListsIdRequest: GetV1ListsIdRequest,
): string {
  return JSON.stringify(
    GetV1ListsIdRequest$outboundSchema.parse(getV1ListsIdRequest),
  );
}
