/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PatchV1QrCodesIdRequestBody = {
  url?: string | undefined;
  name?: string | null | undefined;
  color?: string | undefined;
  showLogo?: boolean | undefined;
  logoUrl?: string | null | undefined;
};

export type PatchV1QrCodesIdRequest = {
  id: string;
  body: PatchV1QrCodesIdRequestBody;
};

/** @internal */
export type PatchV1QrCodesIdRequestBody$Outbound = {
  url?: string | undefined;
  name?: string | null | undefined;
  color?: string | undefined;
  show_logo?: boolean | undefined;
  logo_url?: string | null | undefined;
};

/** @internal */
export const PatchV1QrCodesIdRequestBody$outboundSchema: z.ZodMiniType<
  PatchV1QrCodesIdRequestBody$Outbound,
  PatchV1QrCodesIdRequestBody
> = z.pipe(
  z.object({
    url: z.optional(z.string()),
    name: z.optional(z.nullable(z.string())),
    color: z.optional(z.string()),
    showLogo: z.optional(z.boolean()),
    logoUrl: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      showLogo: "show_logo",
      logoUrl: "logo_url",
    });
  }),
);

export function patchV1QrCodesIdRequestBodyToJSON(
  patchV1QrCodesIdRequestBody: PatchV1QrCodesIdRequestBody,
): string {
  return JSON.stringify(
    PatchV1QrCodesIdRequestBody$outboundSchema.parse(
      patchV1QrCodesIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchV1QrCodesIdRequest$Outbound = {
  id: string;
  body: PatchV1QrCodesIdRequestBody$Outbound;
};

/** @internal */
export const PatchV1QrCodesIdRequest$outboundSchema: z.ZodMiniType<
  PatchV1QrCodesIdRequest$Outbound,
  PatchV1QrCodesIdRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => PatchV1QrCodesIdRequestBody$outboundSchema),
});

export function patchV1QrCodesIdRequestToJSON(
  patchV1QrCodesIdRequest: PatchV1QrCodesIdRequest,
): string {
  return JSON.stringify(
    PatchV1QrCodesIdRequest$outboundSchema.parse(patchV1QrCodesIdRequest),
  );
}
