/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1ListsIdRequest = {
  id: string;
  body: models.ListUpdate;
};

/** @internal */
export type PatchV1ListsIdRequest$Outbound = {
  id: string;
  body: models.ListUpdate$Outbound;
};

/** @internal */
export const PatchV1ListsIdRequest$outboundSchema: z.ZodMiniType<
  PatchV1ListsIdRequest$Outbound,
  PatchV1ListsIdRequest
> = z.object({
  id: z.string(),
  body: models.ListUpdate$outboundSchema,
});

export function patchV1ListsIdRequestToJSON(
  patchV1ListsIdRequest: PatchV1ListsIdRequest,
): string {
  return JSON.stringify(
    PatchV1ListsIdRequest$outboundSchema.parse(patchV1ListsIdRequest),
  );
}
