/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchV1TagsIdRequest = {
  id: string;
  body: models.TagUpdate;
};

/** @internal */
export type PatchV1TagsIdRequest$Outbound = {
  id: string;
  body: models.TagUpdate$Outbound;
};

/** @internal */
export const PatchV1TagsIdRequest$outboundSchema: z.ZodMiniType<
  PatchV1TagsIdRequest$Outbound,
  PatchV1TagsIdRequest
> = z.object({
  id: z.string(),
  body: models.TagUpdate$outboundSchema,
});

export function patchV1TagsIdRequestToJSON(
  patchV1TagsIdRequest: PatchV1TagsIdRequest,
): string {
  return JSON.stringify(
    PatchV1TagsIdRequest$outboundSchema.parse(patchV1TagsIdRequest),
  );
}
