/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PatchV1UtmTemplatesIdRequestBody = {
  name?: string | undefined;
  utmSource?: string | null | undefined;
  utmMedium?: string | null | undefined;
  utmCampaign?: string | null | undefined;
  utmTerm?: string | null | undefined;
  utmContent?: string | null | undefined;
  ref?: string | null | undefined;
};

export type PatchV1UtmTemplatesIdRequest = {
  id: string;
  body: PatchV1UtmTemplatesIdRequestBody;
};

/** @internal */
export type PatchV1UtmTemplatesIdRequestBody$Outbound = {
  name?: string | undefined;
  utm_source?: string | null | undefined;
  utm_medium?: string | null | undefined;
  utm_campaign?: string | null | undefined;
  utm_term?: string | null | undefined;
  utm_content?: string | null | undefined;
  ref?: string | null | undefined;
};

/** @internal */
export const PatchV1UtmTemplatesIdRequestBody$outboundSchema: z.ZodMiniType<
  PatchV1UtmTemplatesIdRequestBody$Outbound,
  PatchV1UtmTemplatesIdRequestBody
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    utmSource: z.optional(z.nullable(z.string())),
    utmMedium: z.optional(z.nullable(z.string())),
    utmCampaign: z.optional(z.nullable(z.string())),
    utmTerm: z.optional(z.nullable(z.string())),
    utmContent: z.optional(z.nullable(z.string())),
    ref: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      utmSource: "utm_source",
      utmMedium: "utm_medium",
      utmCampaign: "utm_campaign",
      utmTerm: "utm_term",
      utmContent: "utm_content",
    });
  }),
);

export function patchV1UtmTemplatesIdRequestBodyToJSON(
  patchV1UtmTemplatesIdRequestBody: PatchV1UtmTemplatesIdRequestBody,
): string {
  return JSON.stringify(
    PatchV1UtmTemplatesIdRequestBody$outboundSchema.parse(
      patchV1UtmTemplatesIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchV1UtmTemplatesIdRequest$Outbound = {
  id: string;
  body: PatchV1UtmTemplatesIdRequestBody$Outbound;
};

/** @internal */
export const PatchV1UtmTemplatesIdRequest$outboundSchema: z.ZodMiniType<
  PatchV1UtmTemplatesIdRequest$Outbound,
  PatchV1UtmTemplatesIdRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => PatchV1UtmTemplatesIdRequestBody$outboundSchema),
});

export function patchV1UtmTemplatesIdRequestToJSON(
  patchV1UtmTemplatesIdRequest: PatchV1UtmTemplatesIdRequest,
): string {
  return JSON.stringify(
    PatchV1UtmTemplatesIdRequest$outboundSchema.parse(
      patchV1UtmTemplatesIdRequest,
    ),
  );
}
