/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PatchV1LinksShortCodeRequestBody = {
  originalUrl?: string | undefined;
  title?: string | null | undefined;
  isActive?: boolean | undefined;
  expireAt?: Date | null | undefined;
  notes?: string | null | undefined;
  listId?: string | null | undefined;
  customDomain?: string | null | undefined;
  /**
   * Rename the short code. Must be unique, ≥ 3 chars, alphanumeric plus hyphens/underscores.
   */
  shortCode?: string | undefined;
};

export type PatchV1LinksShortCodeRequest = {
  shortCode: string;
  body: PatchV1LinksShortCodeRequestBody;
};

/** @internal */
export type PatchV1LinksShortCodeRequestBody$Outbound = {
  original_url?: string | undefined;
  title?: string | null | undefined;
  is_active?: boolean | undefined;
  expire_at?: string | null | undefined;
  notes?: string | null | undefined;
  list_id?: string | null | undefined;
  custom_domain?: string | null | undefined;
  short_code?: string | undefined;
};

/** @internal */
export const PatchV1LinksShortCodeRequestBody$outboundSchema: z.ZodMiniType<
  PatchV1LinksShortCodeRequestBody$Outbound,
  PatchV1LinksShortCodeRequestBody
> = z.pipe(
  z.object({
    originalUrl: z.optional(z.string()),
    title: z.optional(z.nullable(z.string())),
    isActive: z.optional(z.boolean()),
    expireAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    notes: z.optional(z.nullable(z.string())),
    listId: z.optional(z.nullable(z.string())),
    customDomain: z.optional(z.nullable(z.string())),
    shortCode: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      originalUrl: "original_url",
      isActive: "is_active",
      expireAt: "expire_at",
      listId: "list_id",
      customDomain: "custom_domain",
      shortCode: "short_code",
    });
  }),
);

export function patchV1LinksShortCodeRequestBodyToJSON(
  patchV1LinksShortCodeRequestBody: PatchV1LinksShortCodeRequestBody,
): string {
  return JSON.stringify(
    PatchV1LinksShortCodeRequestBody$outboundSchema.parse(
      patchV1LinksShortCodeRequestBody,
    ),
  );
}

/** @internal */
export type PatchV1LinksShortCodeRequest$Outbound = {
  shortCode: string;
  body: PatchV1LinksShortCodeRequestBody$Outbound;
};

/** @internal */
export const PatchV1LinksShortCodeRequest$outboundSchema: z.ZodMiniType<
  PatchV1LinksShortCodeRequest$Outbound,
  PatchV1LinksShortCodeRequest
> = z.object({
  shortCode: z.string(),
  body: z.lazy(() => PatchV1LinksShortCodeRequestBody$outboundSchema),
});

export function patchV1LinksShortCodeRequestToJSON(
  patchV1LinksShortCodeRequest: PatchV1LinksShortCodeRequest,
): string {
  return JSON.stringify(
    PatchV1LinksShortCodeRequest$outboundSchema.parse(
      patchV1LinksShortCodeRequest,
    ),
  );
}
