/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostV1UtmTemplatesRequest = {
  name: string;
  utmSource?: string | null | undefined;
  utmMedium?: string | null | undefined;
  utmCampaign?: string | null | undefined;
  utmTerm?: string | null | undefined;
  utmContent?: string | null | undefined;
  ref?: string | null | undefined;
};

/** @internal */
export type PostV1UtmTemplatesRequest$Outbound = {
  name: string;
  utm_source?: string | null | undefined;
  utm_medium?: string | null | undefined;
  utm_campaign?: string | null | undefined;
  utm_term?: string | null | undefined;
  utm_content?: string | null | undefined;
  ref?: string | null | undefined;
};

/** @internal */
export const PostV1UtmTemplatesRequest$outboundSchema: z.ZodMiniType<
  PostV1UtmTemplatesRequest$Outbound,
  PostV1UtmTemplatesRequest
> = z.pipe(
  z.object({
    name: z.string(),
    utmSource: z.optional(z.nullable(z.string())),
    utmMedium: z.optional(z.nullable(z.string())),
    utmCampaign: z.optional(z.nullable(z.string())),
    utmTerm: z.optional(z.nullable(z.string())),
    utmContent: z.optional(z.nullable(z.string())),
    ref: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      utmSource: "utm_source",
      utmMedium: "utm_medium",
      utmCampaign: "utm_campaign",
      utmTerm: "utm_term",
      utmContent: "utm_content",
    });
  }),
);

export function postV1UtmTemplatesRequestToJSON(
  postV1UtmTemplatesRequest: PostV1UtmTemplatesRequest,
): string {
  return JSON.stringify(
    PostV1UtmTemplatesRequest$outboundSchema.parse(postV1UtmTemplatesRequest),
  );
}
