/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostV1QrCodesRequest = {
  url: string;
  name?: string | null | undefined;
  color?: string | undefined;
  showLogo?: boolean | undefined;
  logoUrl?: string | null | undefined;
};

/** @internal */
export type PostV1QrCodesRequest$Outbound = {
  url: string;
  name?: string | null | undefined;
  color: string;
  show_logo: boolean;
  logo_url?: string | null | undefined;
};

/** @internal */
export const PostV1QrCodesRequest$outboundSchema: z.ZodMiniType<
  PostV1QrCodesRequest$Outbound,
  PostV1QrCodesRequest
> = z.pipe(
  z.object({
    url: z.string(),
    name: z.optional(z.nullable(z.string())),
    color: z._default(z.string(), "#000000"),
    showLogo: z._default(z.boolean(), false),
    logoUrl: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      showLogo: "show_logo",
      logoUrl: "logo_url",
    });
  }),
);

export function postV1QrCodesRequestToJSON(
  postV1QrCodesRequest: PostV1QrCodesRequest,
): string {
  return JSON.stringify(
    PostV1QrCodesRequest$outboundSchema.parse(postV1QrCodesRequest),
  );
}
