/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type Link = {
  originalUrl: string;
  title?: string | null | undefined;
  notes?: string | null | undefined;
  customDomain?: string | null | undefined;
};

export type PostV1LinksBulkRequest = {
  links: Array<Link>;
};

/** @internal */
export type Link$Outbound = {
  original_url: string;
  title?: string | null | undefined;
  notes?: string | null | undefined;
  custom_domain?: string | null | undefined;
};

/** @internal */
export const Link$outboundSchema: z.ZodMiniType<Link$Outbound, Link> = z.pipe(
  z.object({
    originalUrl: z.string(),
    title: z.optional(z.nullable(z.string())),
    notes: z.optional(z.nullable(z.string())),
    customDomain: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      originalUrl: "original_url",
      customDomain: "custom_domain",
    });
  }),
);

export function linkToJSON(link: Link): string {
  return JSON.stringify(Link$outboundSchema.parse(link));
}

/** @internal */
export type PostV1LinksBulkRequest$Outbound = {
  links: Array<Link$Outbound>;
};

/** @internal */
export const PostV1LinksBulkRequest$outboundSchema: z.ZodMiniType<
  PostV1LinksBulkRequest$Outbound,
  PostV1LinksBulkRequest
> = z.object({
  links: z.array(z.lazy(() => Link$outboundSchema)),
});

export function postV1LinksBulkRequestToJSON(
  postV1LinksBulkRequest: PostV1LinksBulkRequest,
): string {
  return JSON.stringify(
    PostV1LinksBulkRequest$outboundSchema.parse(postV1LinksBulkRequest),
  );
}
