/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PostV1HooksRequest = {
  event: models.WebhookEvent;
  targetUrl: string;
};

/** @internal */
export type PostV1HooksRequest$Outbound = {
  event: string;
  target_url: string;
};

/** @internal */
export const PostV1HooksRequest$outboundSchema: z.ZodMiniType<
  PostV1HooksRequest$Outbound,
  PostV1HooksRequest
> = z.pipe(
  z.object({
    event: models.WebhookEvent$outboundSchema,
    targetUrl: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetUrl: "target_url",
    });
  }),
);

export function postV1HooksRequestToJSON(
  postV1HooksRequest: PostV1HooksRequest,
): string {
  return JSON.stringify(
    PostV1HooksRequest$outboundSchema.parse(postV1HooksRequest),
  );
}
