/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostV1LinksRequest = {
  originalUrl: string;
  title?: string | null | undefined;
  customDomain?: string | null | undefined;
  expireAt?: Date | null | undefined;
  notes?: string | null | undefined;
  listId?: string | null | undefined;
};

/** @internal */
export type PostV1LinksRequest$Outbound = {
  original_url: string;
  title?: string | null | undefined;
  custom_domain?: string | null | undefined;
  expire_at?: string | null | undefined;
  notes?: string | null | undefined;
  list_id?: string | null | undefined;
};

/** @internal */
export const PostV1LinksRequest$outboundSchema: z.ZodMiniType<
  PostV1LinksRequest$Outbound,
  PostV1LinksRequest
> = z.pipe(
  z.object({
    originalUrl: z.string(),
    title: z.optional(z.nullable(z.string())),
    customDomain: z.optional(z.nullable(z.string())),
    expireAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    notes: z.optional(z.nullable(z.string())),
    listId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      originalUrl: "original_url",
      customDomain: "custom_domain",
      expireAt: "expire_at",
      listId: "list_id",
    });
  }),
);

export function postV1LinksRequestToJSON(
  postV1LinksRequest: PostV1LinksRequest,
): string {
  return JSON.stringify(
    PostV1LinksRequest$outboundSchema.parse(postV1LinksRequest),
  );
}
