/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostTrackSaleRequest = {
  /**
   * Your Linkkit publishable key (starts with `pk_`)
   */
  publishableKey: string;
  /**
   * Linkkit click ID for attribution (optional)
   */
  lkclid?: string | null | undefined;
  /**
   * Your internal identifier for this customer
   */
  customerExternalId: string;
  customerName?: string | null | undefined;
  customerEmail?: string | null | undefined;
  /**
   * Sale amount in cents
   */
  amount: number;
  /**
   * ISO 4217 currency code (defaults to "usd")
   */
  currency?: string | undefined;
  paymentProcessor?: string | null | undefined;
  invoiceId?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type PostTrackSaleRequest$Outbound = {
  publishable_key: string;
  lkclid?: string | null | undefined;
  customer_external_id: string;
  customer_name?: string | null | undefined;
  customer_email?: string | null | undefined;
  amount: number;
  currency?: string | undefined;
  payment_processor?: string | null | undefined;
  invoice_id?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const PostTrackSaleRequest$outboundSchema: z.ZodMiniType<
  PostTrackSaleRequest$Outbound,
  PostTrackSaleRequest
> = z.pipe(
  z.object({
    publishableKey: z.string(),
    lkclid: z.optional(z.nullable(z.string())),
    customerExternalId: z.string(),
    customerName: z.optional(z.nullable(z.string())),
    customerEmail: z.optional(z.nullable(z.string())),
    amount: z.int(),
    currency: z.optional(z.string()),
    paymentProcessor: z.optional(z.nullable(z.string())),
    invoiceId: z.optional(z.nullable(z.string())),
    metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      publishableKey: "publishable_key",
      customerExternalId: "customer_external_id",
      customerName: "customer_name",
      customerEmail: "customer_email",
      paymentProcessor: "payment_processor",
      invoiceId: "invoice_id",
    });
  }),
);

export function postTrackSaleRequestToJSON(
  postTrackSaleRequest: PostTrackSaleRequest,
): string {
  return JSON.stringify(
    PostTrackSaleRequest$outboundSchema.parse(postTrackSaleRequest),
  );
}
