/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostTrackLeadRequest = {
  /**
   * Your Linkkit publishable key (starts with `pk_`)
   */
  publishableKey: string;
  /**
   * Linkkit click ID for attribution (optional)
   */
  lkclid?: string | null | undefined;
  /**
   * Your internal identifier for this customer
   */
  customerExternalId: string;
  /**
   * Custom event name (defaults to "Lead")
   */
  eventName?: string | undefined;
  customerName?: string | null | undefined;
  customerEmail?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type PostTrackLeadRequest$Outbound = {
  publishable_key: string;
  lkclid?: string | null | undefined;
  customer_external_id: string;
  event_name?: string | undefined;
  customer_name?: string | null | undefined;
  customer_email?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const PostTrackLeadRequest$outboundSchema: z.ZodMiniType<
  PostTrackLeadRequest$Outbound,
  PostTrackLeadRequest
> = z.pipe(
  z.object({
    publishableKey: z.string(),
    lkclid: z.optional(z.nullable(z.string())),
    customerExternalId: z.string(),
    eventName: z.optional(z.string()),
    customerName: z.optional(z.nullable(z.string())),
    customerEmail: z.optional(z.nullable(z.string())),
    metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      publishableKey: "publishable_key",
      customerExternalId: "customer_external_id",
      eventName: "event_name",
      customerName: "customer_name",
      customerEmail: "customer_email",
    });
  }),
);

export function postTrackLeadRequestToJSON(
  postTrackLeadRequest: PostTrackLeadRequest,
): string {
  return JSON.stringify(
    PostTrackLeadRequest$outboundSchema.parse(postTrackLeadRequest),
  );
}
