/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PutV1LinksShortCodeRequestBody = {
  originalUrl: string;
  title?: string | null | undefined;
  customDomain?: string | null | undefined;
  isActive?: boolean | undefined;
  expireAt?: Date | null | undefined;
  notes?: string | null | undefined;
  listId?: string | null | undefined;
};

export type PutV1LinksShortCodeRequest = {
  shortCode: string;
  body: PutV1LinksShortCodeRequestBody;
};

/** @internal */
export type PutV1LinksShortCodeRequestBody$Outbound = {
  original_url: string;
  title?: string | null | undefined;
  custom_domain?: string | null | undefined;
  is_active?: boolean | undefined;
  expire_at?: string | null | undefined;
  notes?: string | null | undefined;
  list_id?: string | null | undefined;
};

/** @internal */
export const PutV1LinksShortCodeRequestBody$outboundSchema: z.ZodMiniType<
  PutV1LinksShortCodeRequestBody$Outbound,
  PutV1LinksShortCodeRequestBody
> = z.pipe(
  z.object({
    originalUrl: z.string(),
    title: z.optional(z.nullable(z.string())),
    customDomain: z.optional(z.nullable(z.string())),
    isActive: z.optional(z.boolean()),
    expireAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    notes: z.optional(z.nullable(z.string())),
    listId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      originalUrl: "original_url",
      customDomain: "custom_domain",
      isActive: "is_active",
      expireAt: "expire_at",
      listId: "list_id",
    });
  }),
);

export function putV1LinksShortCodeRequestBodyToJSON(
  putV1LinksShortCodeRequestBody: PutV1LinksShortCodeRequestBody,
): string {
  return JSON.stringify(
    PutV1LinksShortCodeRequestBody$outboundSchema.parse(
      putV1LinksShortCodeRequestBody,
    ),
  );
}

/** @internal */
export type PutV1LinksShortCodeRequest$Outbound = {
  shortCode: string;
  body: PutV1LinksShortCodeRequestBody$Outbound;
};

/** @internal */
export const PutV1LinksShortCodeRequest$outboundSchema: z.ZodMiniType<
  PutV1LinksShortCodeRequest$Outbound,
  PutV1LinksShortCodeRequest
> = z.object({
  shortCode: z.string(),
  body: z.lazy(() => PutV1LinksShortCodeRequestBody$outboundSchema),
});

export function putV1LinksShortCodeRequestToJSON(
  putV1LinksShortCodeRequest: PutV1LinksShortCodeRequest,
): string {
  return JSON.stringify(
    PutV1LinksShortCodeRequest$outboundSchema.parse(putV1LinksShortCodeRequest),
  );
}
