/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Click = {
  id?: string | undefined;
  clickedAt?: Date | undefined;
  country?: string | null | undefined;
  city?: string | null | undefined;
  device?: string | null | undefined;
  browser?: string | null | undefined;
  os?: string | null | undefined;
  referer?: string | null | undefined;
};

/** @internal */
export const Click$inboundSchema: z.ZodMiniType<Click, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    clicked_at: types.optional(types.date()),
    country: z.optional(z.nullable(types.string())),
    city: z.optional(z.nullable(types.string())),
    device: z.optional(z.nullable(types.string())),
    browser: z.optional(z.nullable(types.string())),
    os: z.optional(z.nullable(types.string())),
    referer: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "clicked_at": "clickedAt",
    });
  }),
);

export function clickFromJSON(
  jsonString: string,
): SafeParseResult<Click, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Click$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Click' from JSON`,
  );
}
