/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ConversionType,
  ConversionType$inboundSchema,
} from "./conversion-type.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ConversionLink = {
  shortCode?: string | undefined;
  title?: string | null | undefined;
  customDomain?: string | null | undefined;
};

export type Conversion = {
  id?: string | undefined;
  type?: ConversionType | undefined;
  eventName?: string | undefined;
  customerExternalId?: string | undefined;
  customerName?: string | null | undefined;
  customerEmail?: string | null | undefined;
  /**
   * Sale amount in cents
   */
  amount?: number | null | undefined;
  currency?: string | null | undefined;
  invoiceId?: string | null | undefined;
  linkId?: string | null | undefined;
  clickId?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  createdAt?: Date | undefined;
  link?: ConversionLink | null | undefined;
};

/** @internal */
export const ConversionLink$inboundSchema: z.ZodMiniType<
  ConversionLink,
  unknown
> = z.pipe(
  z.object({
    short_code: types.optional(types.string()),
    title: z.optional(z.nullable(types.string())),
    custom_domain: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "short_code": "shortCode",
      "custom_domain": "customDomain",
    });
  }),
);

export function conversionLinkFromJSON(
  jsonString: string,
): SafeParseResult<ConversionLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversionLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversionLink' from JSON`,
  );
}

/** @internal */
export const Conversion$inboundSchema: z.ZodMiniType<Conversion, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      type: types.optional(ConversionType$inboundSchema),
      event_name: types.optional(types.string()),
      customer_external_id: types.optional(types.string()),
      customer_name: z.optional(z.nullable(types.string())),
      customer_email: z.optional(z.nullable(types.string())),
      amount: z.optional(z.nullable(types.number())),
      currency: z.optional(z.nullable(types.string())),
      invoice_id: z.optional(z.nullable(types.string())),
      link_id: z.optional(z.nullable(types.string())),
      click_id: z.optional(z.nullable(types.string())),
      metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
      created_at: types.optional(types.date()),
      link: z.optional(z.nullable(z.lazy(() => ConversionLink$inboundSchema))),
    }),
    z.transform((v) => {
      return remap$(v, {
        "event_name": "eventName",
        "customer_external_id": "customerExternalId",
        "customer_name": "customerName",
        "customer_email": "customerEmail",
        "invoice_id": "invoiceId",
        "link_id": "linkId",
        "click_id": "clickId",
        "created_at": "createdAt",
      });
    }),
  );

export function conversionFromJSON(
  jsonString: string,
): SafeParseResult<Conversion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Conversion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Conversion' from JSON`,
  );
}
