/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ConversionType = {
  Lead: "lead",
  Sale: "sale",
} as const;
export type ConversionType = OpenEnum<typeof ConversionType>;

/** @internal */
export const ConversionType$inboundSchema: z.ZodMiniType<
  ConversionType,
  unknown
> = openEnums.inboundSchema(ConversionType);
/** @internal */
export const ConversionType$outboundSchema: z.ZodMiniType<
  string,
  ConversionType
> = openEnums.outboundSchema(ConversionType);
