/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DomainDetail = {
  id?: string | undefined;
  domain?: string | undefined;
  isVerified?: boolean | undefined;
  createdAt?: Date | undefined;
  cnameName?: string | null | undefined;
  cnameValue?: string | null | undefined;
  txtName?: string | null | undefined;
  txtValue?: string | null | undefined;
};

/** @internal */
export const DomainDetail$inboundSchema: z.ZodMiniType<DomainDetail, unknown> =
  z.pipe(
    z.object({
      id: types.optional(types.string()),
      domain: types.optional(types.string()),
      is_verified: types.optional(types.boolean()),
      created_at: types.optional(types.date()),
      cname_name: z.optional(z.nullable(types.string())),
      cname_value: z.optional(z.nullable(types.string())),
      txt_name: z.optional(z.nullable(types.string())),
      txt_value: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "is_verified": "isVerified",
        "created_at": "createdAt",
        "cname_name": "cnameName",
        "cname_value": "cnameValue",
        "txt_name": "txtName",
        "txt_value": "txtValue",
      });
    }),
  );

export function domainDetailFromJSON(
  jsonString: string,
): SafeParseResult<DomainDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DomainDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DomainDetail' from JSON`,
  );
}
