/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Domain = {
  id?: string | undefined;
  domain?: string | undefined;
  isVerified?: boolean | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const Domain$inboundSchema: z.ZodMiniType<Domain, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    domain: types.optional(types.string()),
    is_verified: types.optional(types.boolean()),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_verified": "isVerified",
      "created_at": "createdAt",
    });
  }),
);

export function domainFromJSON(
  jsonString: string,
): SafeParseResult<Domain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Domain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Domain' from JSON`,
  );
}
