/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Link = {
  id?: string | undefined;
  shortCode?: string | undefined;
  originalUrl?: string | undefined;
  title?: string | null | undefined;
  /**
   * Custom domain to use for this link instead of the default uselinkkit.com
   */
  customDomain?: string | null | undefined;
  isActive?: boolean | undefined;
  expireAt?: Date | null | undefined;
  notes?: string | null | undefined;
  listId?: string | null | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const Link$inboundSchema: z.ZodMiniType<Link, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    short_code: types.optional(types.string()),
    original_url: types.optional(types.string()),
    title: z.optional(z.nullable(types.string())),
    custom_domain: z.optional(z.nullable(types.string())),
    is_active: types.optional(types.boolean()),
    expire_at: z.optional(z.nullable(types.date())),
    notes: z.optional(z.nullable(types.string())),
    list_id: z.optional(z.nullable(types.string())),
    created_at: types.optional(types.date()),
    updated_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "short_code": "shortCode",
      "original_url": "originalUrl",
      "custom_domain": "customDomain",
      "is_active": "isActive",
      "expire_at": "expireAt",
      "list_id": "listId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function linkFromJSON(
  jsonString: string,
): SafeParseResult<Link, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Link$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Link' from JSON`,
  );
}
