/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListInput = {
  name: string;
  color?: string | null | undefined;
};

/** @internal */
export type ListInput$Outbound = {
  name: string;
  color?: string | null | undefined;
};

/** @internal */
export const ListInput$outboundSchema: z.ZodMiniType<
  ListInput$Outbound,
  ListInput
> = z.object({
  name: z.string(),
  color: z.optional(z.nullable(z.string())),
});

export function listInputToJSON(listInput: ListInput): string {
  return JSON.stringify(ListInput$outboundSchema.parse(listInput));
}
