/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListUpdate = {
  name?: string | undefined;
  color?: string | null | undefined;
};

/** @internal */
export type ListUpdate$Outbound = {
  name?: string | undefined;
  color?: string | null | undefined;
};

/** @internal */
export const ListUpdate$outboundSchema: z.ZodMiniType<
  ListUpdate$Outbound,
  ListUpdate
> = z.object({
  name: z.optional(z.string()),
  color: z.optional(z.nullable(z.string())),
});

export function listUpdateToJSON(listUpdate: ListUpdate): string {
  return JSON.stringify(ListUpdate$outboundSchema.parse(listUpdate));
}
