/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type MetaTotal = {
  total?: number | undefined;
};

/** @internal */
export const MetaTotal$inboundSchema: z.ZodMiniType<MetaTotal, unknown> = z
  .object({
    total: types.optional(types.number()),
  });

export function metaTotalFromJSON(
  jsonString: string,
): SafeParseResult<MetaTotal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetaTotal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetaTotal' from JSON`,
  );
}
