/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Meta = {
  page?: number | undefined;
  limit?: number | undefined;
  total?: number | undefined;
};

/** @internal */
export const Meta$inboundSchema: z.ZodMiniType<Meta, unknown> = z.object({
  page: types.optional(types.number()),
  limit: types.optional(types.number()),
  total: types.optional(types.number()),
});

export function metaFromJSON(
  jsonString: string,
): SafeParseResult<Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Meta' from JSON`,
  );
}
