/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type QrCode = {
  id?: string | undefined;
  url?: string | undefined;
  name?: string | null | undefined;
  color?: string | undefined;
  showLogo?: boolean | undefined;
  logoUrl?: string | null | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const QrCode$inboundSchema: z.ZodMiniType<QrCode, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    url: types.optional(types.string()),
    name: z.optional(z.nullable(types.string())),
    color: types.optional(types.string()),
    show_logo: types.optional(types.boolean()),
    logo_url: z.optional(z.nullable(types.string())),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "show_logo": "showLogo",
      "logo_url": "logoUrl",
      "created_at": "createdAt",
    });
  }),
);

export function qrCodeFromJSON(
  jsonString: string,
): SafeParseResult<QrCode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QrCode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QrCode' from JSON`,
  );
}
