/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TagInput = {
  name: string;
  color?: string | null | undefined;
};

/** @internal */
export type TagInput$Outbound = {
  name: string;
  color?: string | null | undefined;
};

/** @internal */
export const TagInput$outboundSchema: z.ZodMiniType<
  TagInput$Outbound,
  TagInput
> = z.object({
  name: z.string(),
  color: z.optional(z.nullable(z.string())),
});

export function tagInputToJSON(tagInput: TagInput): string {
  return JSON.stringify(TagInput$outboundSchema.parse(tagInput));
}
