/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TagUpdate = {
  name?: string | undefined;
  color?: string | null | undefined;
};

/** @internal */
export type TagUpdate$Outbound = {
  name?: string | undefined;
  color?: string | null | undefined;
};

/** @internal */
export const TagUpdate$outboundSchema: z.ZodMiniType<
  TagUpdate$Outbound,
  TagUpdate
> = z.object({
  name: z.optional(z.string()),
  color: z.optional(z.nullable(z.string())),
});

export function tagUpdateToJSON(tagUpdate: TagUpdate): string {
  return JSON.stringify(TagUpdate$outboundSchema.parse(tagUpdate));
}
