/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Tag = {
  id?: string | undefined;
  name?: string | undefined;
  color?: string | null | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const Tag$inboundSchema: z.ZodMiniType<Tag, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    color: z.optional(z.nullable(types.string())),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function tagFromJSON(
  jsonString: string,
): SafeParseResult<Tag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tag' from JSON`,
  );
}
