/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UtmTemplate = {
  id?: string | undefined;
  name?: string | undefined;
  utmSource?: string | null | undefined;
  utmMedium?: string | null | undefined;
  utmCampaign?: string | null | undefined;
  utmTerm?: string | null | undefined;
  utmContent?: string | null | undefined;
  ref?: string | null | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const UtmTemplate$inboundSchema: z.ZodMiniType<UtmTemplate, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      utm_source: z.optional(z.nullable(types.string())),
      utm_medium: z.optional(z.nullable(types.string())),
      utm_campaign: z.optional(z.nullable(types.string())),
      utm_term: z.optional(z.nullable(types.string())),
      utm_content: z.optional(z.nullable(types.string())),
      ref: z.optional(z.nullable(types.string())),
      created_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "utm_source": "utmSource",
        "utm_medium": "utmMedium",
        "utm_campaign": "utmCampaign",
        "utm_term": "utmTerm",
        "utm_content": "utmContent",
        "created_at": "createdAt",
      });
    }),
  );

export function utmTemplateFromJSON(
  jsonString: string,
): SafeParseResult<UtmTemplate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UtmTemplate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UtmTemplate' from JSON`,
  );
}
