/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const WebhookEvent = {
  LinkCreated: "link.created",
  LinkUpdated: "link.updated",
  LinkDeleted: "link.deleted",
  LinkClicked: "link.clicked",
} as const;
export type WebhookEvent = OpenEnum<typeof WebhookEvent>;

/** @internal */
export const WebhookEvent$inboundSchema: z.ZodMiniType<WebhookEvent, unknown> =
  openEnums.inboundSchema(WebhookEvent);
/** @internal */
export const WebhookEvent$outboundSchema: z.ZodMiniType<string, WebhookEvent> =
  openEnums.outboundSchema(WebhookEvent);
