/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { WebhookEvent, WebhookEvent$inboundSchema } from "./webhook-event.js";

export type Webhook = {
  id?: string | undefined;
  event?: WebhookEvent | undefined;
  url?: string | undefined;
  /**
   * HMAC-SHA256 secret used to verify payloads. Store this securely — it is only returned on creation.
   */
  secret?: string | undefined;
  isActive?: boolean | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const Webhook$inboundSchema: z.ZodMiniType<Webhook, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    event: types.optional(WebhookEvent$inboundSchema),
    url: types.optional(types.string()),
    secret: types.optional(types.string()),
    is_active: types.optional(types.boolean()),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_active": "isActive",
      "created_at": "createdAt",
    });
  }),
);

export function webhookFromJSON(
  jsonString: string,
): SafeParseResult<Webhook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Webhook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Webhook' from JSON`,
  );
}
