/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Role = {
  Owner: "owner",
  Admin: "admin",
  Member: "member",
} as const;
export type Role = OpenEnum<typeof Role>;

export type Workspace = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  color?: string | null | undefined;
  logoUrl?: string | null | undefined;
  plan?: string | undefined;
  role?: Role | undefined;
  joinedAt?: Date | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = openEnums
  .inboundSchema(Role);

/** @internal */
export const Workspace$inboundSchema: z.ZodMiniType<Workspace, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      slug: types.optional(types.string()),
      color: z.optional(z.nullable(types.string())),
      logo_url: z.optional(z.nullable(types.string())),
      plan: types.optional(types.string()),
      role: types.optional(Role$inboundSchema),
      joined_at: types.optional(types.date()),
      created_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "logo_url": "logoUrl",
        "joined_at": "joinedAt",
        "created_at": "createdAt",
      });
    }),
  );

export function workspaceFromJSON(
  jsonString: string,
): SafeParseResult<Workspace, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Workspace$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Workspace' from JSON`,
  );
}
